site_name: White Ravens Services Documentation
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  language: pl
  icon:
    logo: material/vector-difference
  palette: 
    # Palette toggle for dark mode
    - scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-7
        name: Tryb dzienny
    # Palette toggle for light mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Tryb nocny
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
    - tags
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@whiteravens
    - icon: fontawesome/brands/discord
      link: https://discord.gg/5JMk8Z4
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/whiteravensgaming
    - icon: fontawesome/brands/github 
      link: https://github.com/whiteravens20
    - icon: simple/kofi
      link: https://ko-fi.com/N4N4E0LR2
  analytics:
    provider: custom
#    property:
  status:
    wrmembers: Wewnętrzna usługa White Ravens
    new: Ostatnio dodane
    deprecated: Wymaga aktualizacji
copyright: Copyright &copy; 2024-2025 White Ravens 2.0

nav:
  - White Ravens Home: https://whiteravens.net
  - Dokumentacja:
    - 'Strona Główna':
      - 'Strona Główna': index.md
      - 'Zgłaszanie błędow': bugs.md
      - 'Bezpieczeństwo haseł': passwordsec.md
#      - 'Tagi': tags.md
    - 'Social':
      - 'Discord': discord.md
      - 'Mastodon': mastodon.md
      - 'Steam': steam.md
    - 'Usługi White Ravens':
      - 'Element Chat': chat.md
      - 'Metawyszukiwarka': search.md
      - 'ShareHub': share.md
      - 'Invidious': invidious.md
      - 'Habitica': habitica.md
  - Dashboard: https://home.wrservices.link
  - Status Usług: https://status.wrservices.link
  - GitHub: https://github.com/whiteravens20